### ISSUE TITLE
PUT /admin/:courseID

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#1]
Add the ability to create a new course. Only admins should be able to do this. This should be wired up to mongo to create a new empty course instance. If the course already exists it should fail.

**Comment by rtholmes** [comment]
Updated title based on our discussion earlier. Only 'super admins' should be able to do this.

**Comment by rtholmes** [comment]
Some fields that will want to go along with this are:

* courseID (string) (e.g., cs310)
* courseName (string) (e.g., CS310: Introduction to Software Engineering)
* minTeamSize (number)
* maxTeamSize (number)
* studentsSetTeams (boolean) (aka can the students create their own teams)
* admins (string[]) (e.g., who will be administering the course going forward)

**Comment by andrewstec** [comment]
Model updated to reflect these changes.

**Comment by rtholmes** [comment]
I don't know if this route needs a GET; are we going to provide an interface for this? For now I say no because this just opens a whole extra set of UI for managing courses.

**Comment by andrewstec** [comment]
We can provide an interface for this. I don't know if it is necessary yet either. It shouldn't take long to implement if you want to tentatively implement it ahead of time.

**Comment by andrewstec** [comment]
I can confirm that /admin/:courseID PUT is operational. 

Please feel free to reopen this issue if we decide that we want a GET for the interface.
