### ISSUE TITLE
POST /:courseId/admin/deliverables

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#10]
Creating a course will create a default empty deliverable list, so all updates will be handled by POST instead of PUT. We will always send all deliverables with the POST instead of just an individual one (since there are just so few).

The payload is the same as #9.

**Comment by andrewstec** [comment]
Endpoint created.

- Based on payload of #9
- Deliverable object contains reference to parent Course objectId.
- Course object contains empty Deliverable list, which contains references to child deliverable objectIds when Deliverables are created.
