### ISSUE TITLE
POST /:courseId/admin/admins

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#11]
We need a way to update the admin list. The more I think about it the more this drives me to thinking we should just have a separate admin and student object for each course. If we maintain a global one it should only be for github tokens and nothing else.

Since there will be a default (empty) list of admins for each course, we can just send all admin details along with the POST. This POST should only succeed if it is submitted by an admin who is a 'prof' or by the portal `superAdmin`.

```
[
  {
    id: githubId,
    firstName: firstName,
    lastName: lastName,
    role: roleKind  ('prof', 'gta', 'uta')
  }
...
]
```

**Comment by andrewstec** [comment]
Endpoint completed.

Payload naming slightly modified to match model names with the same underlying semantic meaning:

[
  {
    username: githubId,
    fname: firstName,
    lname: lastName,
    role: roleKind  ('prof', 'gta', 'uta')
  }
...
]
