### ISSUE TITLE
GET /:courseId/grades

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#13]
This will return grade objects for a student. The objects should _only_ return the grades that have been released (this will be a flag on the deliverable object). The payload should be the same as #4 .

**Comment by andrewstec** [comment]
Endpoint implemented.

- Returns only the grades that have been released, based on the Deliverable object.
- Added logic that Grades are only returned based on the logged in SNUM. Thus, people cannot retrieve grades of other students unless through the authorized Admin endpoint to retrieve all grades.
- Payload from #4.
