### ISSUE TITLE
GET /courses

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#16]
Need a mechanism to get a list of courses; this will be used by the front page so students and admins can choose the class they are accessing.

```
[
  {
    id: courseId,
    name: courseName,
    icon: courseIconUrl
  },
...
]
```

**Comment by andrewstec** [comment]
Endpoint and specifications have been added.

What are your thoughts about adding a Semester/Year field to query courses by? This list could get long in a couple of years. 

Alternatively, an endpoint to remove a particular course could be helpful, but maybe not the preferable option for keeping records.

**Comment by rtholmes** [comment]
I don't think this is needed. These will be transient information and will be purged after the term is over. Yes, we will need to add a DELETE endpoint somewhere (although that was part of the superadmin functionality I was trying to defer for now).

**Comment by andrewstec** [comment]
Sounds good! That makes perfect sense.

**Comment by andrewstec** [comment]
Created endpoint.
