### ISSUE TITLE
PUT /:courseId/admin/github/team

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#19]
Create a team in a GitHub Org:
```
{
  org: 'orgName',
  name: 'teamName',
  members: ['githubid', 'githubid1'...]
}
```

**Comment by stecler** [comment]
Hi Reid,

Quick question.

Do we want to set the org or 'orgName' in a config file, or would you like to keep it as part of this payload? 

Do you anticipate other courses using different organizations?

Thanks!

**Comment by rtholmes** [comment]
Org will definitely vary course to course. It could be stored in the per-course config, but to keep the `createTeam` API flexible you might as well just pass the arg along.

**Comment by stecler** [comment]
Sounds great. Consider it done. Thanks!

**Comment by thekitsch** [comment]
Endpoint completed based on Payload above.

**Comment by stecler** [comment]
Endpoint completed based on payload above.
