### ISSUE TITLE
POST /:courseId/admin/students

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#2]
Enable a CSV to be put to the classList endpoint; should be POST because technically it is 'updating' the empty list that would be created when the course was originally created (via the PUT in Issue #1). Should also add all of the empty student rows to the right course in the database.

**Comment by rtholmes** [comment]
Updated title based on our discussion earlier. Only super admins and admins for the course should be able to do this.

**Comment by rtholmes** [comment]
I think we should rename this from /classList to /students to match the GET in #7 .

**Comment by andrewstec** [comment]
We can do that. 

I can confirm that: 
- the order of the parameters in the URL have changed from /classList/:courseId to /courseId:/classList
- 'admin' was added into the parameters to match authentication. ie. /courseId:/admin/classList
- the /classList parameter has changed to /students
