### ISSUE TITLE
PUT /:courseId/admin/github/repo

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#20]
Create a repo in a GitHub org; members/memberTeams have write but not admin; admins have full admin rights:

```
{
  org: 'orgName',
  name: 'projectName',
  members: ['githubid', 'githubid1'...], // can be []
  memberTeams: ['githubTeam1', 'githubTeam2'...], // can be []
  admins: ['githubid', 'githubid1'...], // can be []
  adminTeams: ['githubTeam1', 'githubTeam2'...], // can be []
  importUrl: '' // empty string or absent means no import, otherwise this will be an importUrl to an existing (public) GitHub Project
}
```

**Comment by stecler** [comment]
Hi Reid,

Quick question. Is there an expectation that the adminTeams and memberTeams already exist in the organization? On the one hand, it appears that the teams in memberTeams[] and adminTeams[] already exists on Github, as a team names exist in the payload. On the other hand, there could be an expectation that the team name in the payload is used to create a new team, as we could create the team on the fly with the team name in the payload. I think your intention is the former option, but I see that completeTeamProvisions() creates the teams on the fly, by first addMembersToTeam(teamId, inputGroup.members) and then addTeamToRepo(teamId, inputGroup.projectName, TEAM_PERMISSIONS).

**Comment by stecler** [comment]
(Unrelated to the question above, I am just breaking this into steps for my own peace off mind)

Breaking this into steps: 

1) Create a new repo with the importUrl with projectName.
- importRepoToNewRepo(projectName, importUrl)
2) Check that repo is made before adding any team members.
- based on if importRepoToNewRepo() : Promise does not result in an error.
3) Add existing members team.
4) Add existing admins to team.
- Based on 3 not returning an error, 
5) Add team members from list by Github username.
- addTeamToRepo(teamId: number, repoName: string, permission: string)
6) Add admin members from list by Github username.
- addTeamToRepo(teamId: number, repoName: string, permission: string)

**Comment by rtholmes** [comment]
For team creation, I think creating a team with a name that already exists should fail, so the whole flow would just stop (via triggering a catch instead of hitting all the thens) and nothing would happen.

**Comment by rtholmes** [comment]
I don't think you need to do step 2; checking the creation will have the same problem my 5s delay tries to solve. One thing you could do though is check in step 0 if the repo exists, and if it does just not provision that repo (or instead trigger a process that verifies the team and team members for that repo are correct).

**Comment by stecler** [comment]
I absolutely agree that the check to see if a repo exists should occur first. That's an easy way to go about avoiding the 5 second delay issue and the process cannot begin so nothing has to be reverted. Very good call.

Thanks for the insight!

**Comment by stecler** [comment]
Endpoint complete. Minor async issue with testing that needs to be ironed out before tests pass.

**Comment by rtholmes** [comment]
Closing this as done, but we should make sure the process of adding a new course is well documented for future terms!
