### ISSUE TITLE
POST /:courseId/admin/grades/:delivId

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#22]
The above endpoint exists, but we'll need a way to also send a CSV to it (probably a different endpoint?). The `delivId` will be used to map into the grades object; for now we can assume this will only work on deliverables that take a single `grade` value.

The CSV columns will be:

```
| snum | grade |
```

Really the only time this would happen is for uploading midterm and final exam grades, but every course does this so support will be needed.

**Comment by andrewstec** [comment]
That's a great idea. I'll get on that very shortly. 

Do you foresee an indexed array that has the SNUM and GRADE fields also being submitted from the front-end for manual entries? The logic wouldn't change much if we decided to implement that in the near future too. That is a potential feature that we could keep in mind, based on the CSV logic.

**Comment by rtholmes** [comment]
I predict the indexed array version will be used by your UI, but not uploaded directly by a user.

**Comment by andrewstec** [comment]
This endpoint has been added and its tests are passing.
