### ISSUE TITLE
GET /:courseId/admin/grades (CSV)

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#23]
This endpoint exists, but we need a similar one for retrieving a CSV. 

One thing we will need to think about is how to add params to our get requests in a coherent manner. Is adding a `?format=csv` the right way to do this for this route, or do we want to do it another way?

**Comment by andrewstec** [comment]
We have decided that ?format=csv will work with Restify, and are not working on the implementation.

**Comment by andrewstec** [comment]
CSV export feature is created. I am currently writing tests for this endpoint.

**Comment by andrewstec** [comment]
Tests passing.

**Comment by rtholmes** [comment]
@stecler If this route works, is there a way for Elisa or Paul to be able to invoke it with `curl` so they can at least get a CSV of the current grades for their courses to see how people are doing?

**Comment by stecler** [comment]
@rtholmes 

Sorry I missed this message earlier. 

We can certainly let Elisa or Paul invoke the route with Curl. The Grade models have to be submitted to the database first though. At the moment, they are in the database as result records. A query of the last `commit`, `username` and `deliverable` will retrieve the grade of the student.

The quickest way of doing this would be by creating a result record schema and bypassing the submission of grades to the Grade Record, and running the query for each latest record based on the three criteria per course. 

This is certainly next in line after tomorrow's D1, D2, D3 release. I understand that they need this information ASAP.

**Comment by rtholmes** [comment]
This sounds more complicated than I thought. If you have a plan to get the grade UI set for the students and staff, I don't want this to slow down your progress. It sounds like this will be easier once that work is in place and grade records are ready anyways.

**Comment by rtholmes** [comment]
We can get this from the UI now so we don't actually need the CURL route. Closing.
