### ISSUE TITLE
Sorting by arbitrary columns in the Students view

### ISSUE THREAD

**Issue by elisabaniassad** [ubccpsc/classportal-backend#25]
So this is my first issue, and I don't want to sound picky, but it would be SO GREAT if we could sort by team number, or specific grade columns. Right now I find myself copying the entire thing to a spreadsheet and sorting from there!  
Thanks so much!!!
THIS IS SO FUN!

**Comment by andrewstec** [comment]
We'll leave this issue open until this request is implemented. It should be fairly straightforward to implement pagination and sorting tables. 

I think we can sort this issue right out.

**Comment by elisabaniassad** [comment]
Oh oops - I just closed it so that I could move it to the UI issues list.

**Comment by rtholmes** [comment]
Fixed by past work with the Table component.
