### ISSUE TITLE
/container route

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#38]
Could we also have a route to get an identifier for the right container for a deliverable? Something like this:

`GET https://URL/:courseId/:delivId/container` --> some kind of `containerId` string in a response body. (`:delivId` is there so we can support both one-container-per-course IDs and specific-containers-per-deliverable IDs.

As with the `/rate` route, this can just be public so we don't need to know about authentication, etc.

**Comment by rtholmes** [comment]
There is actually more we will want here, since we're returning a json object anyways.
```
{ 
    timeout: number, // I know we don't track this in the UI yet; we can add the field or just hard code it at 300s for now
    containerId: string, // this is already on the deliv page
    regressionDelivIds: string[] | [] // this is the regression suites on the deliv page
}
```

**Comment by andrewstec** [comment]
@rtholmes The container tag name and the regressionDelivIds can be retrieved. There is currently no way to grab the timeout, as it is set in the Dockerfile. ie. "CMD timeout 2m /run-tests.sh >/output/stdio.txt 2>&1"

That is something that we can take a look at when we go back into the container build and drop automation.

**Comment by rtholmes** [comment]
Ok, ignore the timeout and just go with `containerId` and `regressionDelivIds` then. Thanks!

**Comment by rtholmes** [comment]
Actually, since we're in there anyways, maybe we should combine this with the `getTestDelay` endpoint and add a `testDelay` field into this `container` endpoint so we can get rid of `getTestDelay`.

**Comment by andrewstec** [comment]
That works for sure. It will be done.

**Comment by andrewstec** [comment]
@rtholmes 

The docker image will also have a separate build field. I made the docker image properties consistent with the deliverable properties. It will get confusing soon if those property names deviate, as Docker calls them different things in different areas too.

**Comment by andrewstec** [comment]
Here is an example of the payload: 

{
    "response": {
        "dockerImage": string;
        "dockerBuild": string;
        "testDelay": number (in seconds),
        "regressionDelivNames": string (space delineated names)
    }
}

**Comment by rtholmes** [comment]
Could `regressionDelivNames` be a `string[]`, just so the clients don't need to take a dependency on the internal format used inside the UI/database for storing these?

**Comment by andrewstec** [comment]
Yes, updating it to a string[] now.

**Comment by andrewstec** [comment]
Done. Ready to push to production if there are no other changes.

**Comment by rtholmes** [comment]
sounds great, good to deploy!

**Comment by rtholmes** [comment]
is `/container` set as an admin route? I'm getting 401 errors trying to hit it. Could we make it a public route again?

**Comment by rtholmes** [comment]
is `/container` set as an admin route? I'm getting 401 errors trying to hit it. Could we make it a public route again?

**Comment by andrewstec** [comment]
You are correct. I have removed the admin middleware and tested it in production. No permissions are needed any longer.

Sorry!
