### ISSUE TITLE
/defaultDeliverable endpoint should return most recently opened

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#39]
Currently the `defaultDeliverable/` endpoint is returning `d1` for 310, but it should be returning `d2` given the dates set for `d0/d1/d2` (all three are currently open, but d2 has the latest start date.

**Comment by rtholmes** [comment]
Hopefully this is just a quick fix, could we get this rolled out on Tuesday?

**Comment by andrewstec** [comment]
@rtholmes I am taking a look at this right now.

**Comment by andrewstec** [comment]
@rtholmes Fixed in production.

**Comment by rtholmes** [comment]
Thanks, works great!
