### ISSUE TITLE
POST /:courseId/admin/grades

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#4]
The payload should look like:
```
[ 
 { snum: studentNumber,
   deliv: string,
  details: {}
}, ...
]
```

For now don't worry about `details`, it'll be an object we will have to figure out. The update should _only_ update rows that are included in the POST (e.g., the absence of a row should not trigger a delete.

**Comment by andrewstec** [comment]
Endpoint has been created.

**Comment by andrewstec** [comment]
I made a very small assumption that the 'details' object has a 'finalGrade' property.

We can always change this later. I made the assumption so that we can pull a mock grade in a CSV file to ensure that the 'snum' and 'grades' column have valid data.
