### ISSUE TITLE
POST /:courseId/admin/team

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#6]
Sometimes admins need to update teams (e.g., to remove a specific member or add a new one). The payload here will just be a list of ids of who should be in the new team.

NOTE: this is a advanced route (aka, not needed for the initial version)

**Comment by andrewstec** [comment]
- This route has been created, as it was easily fit into the refactoring for the original PUT.

**Comment by andrewstec** [comment]
As issue #8 shows a TAs property that is not included in this POST, I am briefly re-opening this issue to include updates to the TAs property. 

I realize that we have admins under courses already, but I would imagine that, even though TAs are technically admins, you would still like to assign TAs to teams in case there is a large number of students in a course. That would allow you to assign a TA to grade team work, etc., and keep track of the work.

**Comment by andrewstec** [comment]
Endpoint updated.

The endpoint structure has been changed to this payload based on parent relationships and specifying the model that needs updating: 

teamId: team Mongoose object ID to be updated,
updatedModel: {
   course: objectId,
   deliverable: objectId,
   teamId: number,
   githubUrl: github url (string),
   members: [user object Id...],
}
