### ISSUE TITLE
GET /:courseId/admin/teams

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#8]
Gets the list of teams (data for the teams tab in the current version):

```
[
  {
    id: teamId, (number)
    url: githubUrl,
    members: [array of student objects],
    TAs: [array of admin user objects, can be empty]
  }
...
]
```

**Comment by andrewstec** [comment]
Just to double-check, would you like Team Names to exist? We can always call them a number based on the order of their creation as well.

**Comment by rtholmes** [comment]
I feel like we don't want to constrain ourselves on this right now; I would leave the names as a string (aka change the schema above) and for now just call each team `Team_<NUM-TEAMS>`.

**Comment by rtholmes** [comment]
One other option is to leave `id` as a number and adding a `name` that is a string.

**Comment by andrewstec** [comment]
Good call. I like the simplicity of adding a name field. Consider it done. It's easy to remove later if we don't need it.

**Comment by andrewstec** [comment]
Tests completed & endpoint updated.
