### ISSUE TITLE
GET /:courseId/deliverables

### ISSUE THREAD

**Issue by rtholmes** [ubccpsc/classportal-backend#9]
Gets the data needed for the deliverables tab in the admin interface (or the deliverables view in the student interface):

```
[
  {
    id: deliverableId,
    name: deliverableName,
    url: URL,
    open: openDate, (need to settle on a date format)
    close: closeDate (need to settle on a date format),
    isReleased: boolean (need to trigger release of grades to students manually)
  }
...
]
```

**Comment by andrewstec** [comment]
Just to double-check, would you like this Deliverable tied into a particular course? 

Based off of the :courseId/ parameter, I am going to implement that by adding a new field to the Delierable model to hold a Course objectId reference.

**Comment by rtholmes** [comment]
Yes, each deliverable will be associated with only one course instance.

**Comment by andrewstec** [comment]
Roger that. Thanks!

**Comment by andrewstec** [comment]
Endpoint created.

Minor note, changed property _isReleased_ to _gradesReleased_.
